- - "PSNR"
  - _target_: medvae.metrics.PSNR
- - "MSE"
  - _target_: medvae.metrics.MSE
- - "MS-SSIM"
  - _target_: medvae.metrics.MS_SSIM
- - "FID-Inception"
  - _target_: medvae.metrics.FID_Inception_3D
- - "FID-CLIP"
  - _target_: medvae.metrics.FID_CLIP_3D