- - "PSNR"
  - _target_: medvae.metrics.PSNR
- - "MSE"
  - _target_: medvae.metrics.MSE
- - "FID-Inception"
  - _target_: medvae.metrics.FID_Inception
- - "FID-CLIP"
  - _target_: medvae.metrics.FID_CLIP
    version: CLIP